name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        source: "build/libs/*.jar"
        target: "/home/ubuntu/app/backend"

    - name: Restart Backend Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "[1] 기존 서버 종료 중..."
          pkill -f 'java -jar' || echo "기존 서버가 이미 종료되어 있거나 실행 중이지 않음"
    
          echo "[2] 5초 대기 중..."
          sleep 5
    
          echo "[3] 서버 재시작 중..."
          nohup java -jar /home/ubuntu/app/backend/*.jar > /home/ubuntu/app/backend/log.out 2>&1 &
    
          echo "[4] 실행 완료. 현재 프로세스 확인:"
          ps -ef | grep java

